#!name=Spotify去广告
#!desc=2026.04.17 部分解锁premium,音质不能设置为超高
# 仓库地址 https://github.com/app2smile/rules
# 功能: 1.去除播放广告 2.歌手/专辑列表正常展示 3.去除随机播放

[Header Rewrite]
# if-none-match返回304状态码
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[MITM]
hostname = %APPEND% spclient.wg.spotify.com, *spclient.spotify.com

[Script]
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js
spotify-proto-ev3 = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-proto-ev3.js,script-update-interval=0
