#!name=Spotify去广告
#!desc=Spotify去广告加部分解锁会员功能,音质不能设置为超高,【二选一启用 EV1 / EV3】
#!icon=https://img.icons8.com/?size=100&id=ZuQiaFCa1vXe&format=png&color=000000
#!date=260416

[Arguments]
spot-ev3-enable = true
spot-ev1-enable = false

[Rule]
AND,((DOMAIN-SUFFIX, spotify.com), (PROTOCOL, QUIC)),REJECT

[URL Rewrite]
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize header-del If-None-Match

# 屏蔽设置界面会员信息（仅影响展示）
^https:\/\/.*-spclient\.spotify\.com(:443)?\/pam-view-service\/ - reject

# 屏蔽 AI DJ
^https:\/\/.*37i9dQZF1EYkqdzj48dyYq - reject

[MITM]
hostname = spclient.wg.spotify.com, *.spclient.spotify.com

[Script]
http-request ^https:\/\/(.*-spclient\.spotify\.com(:443)?|spclient\.wg\.spotify\.com)\/gabo-receiver-service \
script-path=https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-gabo.js, \
timeout=10, tag=spotify-gabo

http-response ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)(\?.*)?$ \
script-path=https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-proto-eevee.js, \
requires-body=true, binary-body-mode=true, timeout=10, tag=Ev_spotifyProto, argument=spot-ev1-enable, enabled=spot-ev1-enable

http-response ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)(\?.*)?$ \
script-path=https://raw.githubusercontent.com/Amlabort/MY_clash/refs/heads/main/files/lpx/js/spot-proto-ev3.js, \
requires-body=true, binary-body-mode=true, timeout=10, tag=Ev3_spotifyProto, argument=spot-ev3-enable, enabled=spot-ev3-enable
